/*function doSomething(){

    return new Promise((resolve, reject)=>{
        let error = false;
        if (!error){
            resolve("You have fetched data !!!");

        }
        else {
            reject("Something went wrong !!!");
        };
    });
};
console.log("Hello 1");
doSomething()
.then(nice=>console.log(nice))
.catch(err=>console.log(err));
console.log("Hello 2");*/